### ISSUE TITLE
Is aiops-incoming-listener a candidate for swagger API?

### ISSUE THREAD

**Issue by AparnaKarve** [ManageIQ/aiops-incoming-listener#13]
`aiops-incoming-listener` is not a flask application unlike the other microservices, reason being it does not require any POST request triggers -- it runs on the main thread and starts listening to messages right away.
Hence, it cannot be considered for adding the Swagger API specification because of the current design.

Should we convert it to a flask application and at least add the `version` endpoint?

This discussion is also related to Prometheus metrics, since in order to collect the metrics, we would need the microservices to have a `metrics` endpoint.

@tumido Any suggestions/thoughts on this?

**Comment by tumido** [comment]
BTW, I think, we should probably have such discussions in JIRA, rather than here. This place might not be visible enough for the rest of the team, since the tasks are tracked there... 

Ok, let's step back first and look at the whole picture:
1. Swagger is an library for describing APIs. It's nice to have it when you want to have clients accessing the API - so they can clearly see what resources are available, on which endpoint, etc.
2. This microservice doesn't serve any API. No client is expected to "go" to this service and query for data/initiate an action.

And since there's no API, what would be the benefit of having an API descriptor? I see none. Can you see any real life scenario, where there's a client accessing an API, where's just a `version` endpoint and nothing else?

Converting this microservice to a server with API just to be able support a tool doesn't make much sense to me. Tools should be used where we can benefit from them. Not just for the sake of having the tool...

Discussion about Prometheus is quite connected topic, I agree, though for such services (without API) Prometheus enables something called PUSH metrics. Please see [prometheus/pushgateway](https://github.com/prometheus/pushgateway).

**Comment by AparnaKarve** [comment]
From my reading so far about Prometheus, the info that I have about the pushgateway approach is that it may have some caveats... the MnM document specifically mentions this as well, hence wanted to be doubly sure before proceeding with either approach.

Let's resume this discussion in JIRA.
Thanks for your input.

**Comment by tumido** [comment]
Discussion moved to [AIOPS-73](https://projects.engineering.redhat.com/browse/AIOPS-73)
